// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.34.1
// source: attestation.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Attestation is the classic-mode message: one attestation per Publish.
type Attestation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeNum       int32                  `protobuf:"varint,1,opt,name=node_num,json=nodeNum,proto3" json:"node_num,omitempty"`
	SlotNum       int32                  `protobuf:"varint,2,opt,name=slot_num,json=slotNum,proto3" json:"slot_num,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	MsgIndex      int32                  `protobuf:"varint,6,opt,name=msg_index,json=msgIndex,proto3" json:"msg_index,omitempty"`
	Signature     []byte                 `protobuf:"bytes,7,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attestation) Reset() {
	*x = Attestation{}
	mi := &file_attestation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attestation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attestation) ProtoMessage() {}

func (x *Attestation) ProtoReflect() protoreflect.Message {
	mi := &file_attestation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attestation.ProtoReflect.Descriptor instead.
func (*Attestation) Descriptor() ([]byte, []int) {
	return file_attestation_proto_rawDescGZIP(), []int{0}
}

func (x *Attestation) GetNodeNum() int32 {
	if x != nil {
		return x.NodeNum
	}
	return 0
}

func (x *Attestation) GetSlotNum() int32 {
	if x != nil {
		return x.SlotNum
	}
	return 0
}

func (x *Attestation) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Attestation) GetMsgIndex() int32 {
	if x != nil {
		return x.MsgIndex
	}
	return 0
}

func (x *Attestation) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// BatchedAttestation carries attestations from multiple committee members
// that share the same attestation data. `attestor_indices` is a list of
// committee positions (0..committee_size-1) whose attestor contributed a
// signature. Positions fit in uint16 for committee_size<=65535; we use
// repeated uint32 so proto3 varint keeps the wire size close to a packed
// uint16 array (1 byte for positions 0..127, 2 bytes for 128..16383).
// Signatures are listed in the same order as `attestor_indices` (typically
// ascending, but order is determined by the encoder).
type BatchedAttestation struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AttestationData []byte                 `protobuf:"bytes,1,opt,name=attestation_data,json=attestationData,proto3" json:"attestation_data,omitempty"`         // opaque AttestationData (sized to attestation_data_size)
	AttestorIndices []uint32               `protobuf:"varint,2,rep,packed,name=attestor_indices,json=attestorIndices,proto3" json:"attestor_indices,omitempty"` // committee positions; values < committee_size
	Signatures      [][]byte               `protobuf:"bytes,3,rep,name=signatures,proto3" json:"signatures,omitempty"`                                          // one per element of attestor_indices
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BatchedAttestation) Reset() {
	*x = BatchedAttestation{}
	mi := &file_attestation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchedAttestation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchedAttestation) ProtoMessage() {}

func (x *BatchedAttestation) ProtoReflect() protoreflect.Message {
	mi := &file_attestation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchedAttestation.ProtoReflect.Descriptor instead.
func (*BatchedAttestation) Descriptor() ([]byte, []int) {
	return file_attestation_proto_rawDescGZIP(), []int{1}
}

func (x *BatchedAttestation) GetAttestationData() []byte {
	if x != nil {
		return x.AttestationData
	}
	return nil
}

func (x *BatchedAttestation) GetAttestorIndices() []uint32 {
	if x != nil {
		return x.AttestorIndices
	}
	return nil
}

func (x *BatchedAttestation) GetSignatures() [][]byte {
	if x != nil {
		return x.Signatures
	}
	return nil
}

// CommitteeAttestationPartsMetadata is the per-AttestationData gossip control
// envelope. `available` advertises the positions the sender holds; `requests`
// is a non-persistent IWANT — the receiver satisfies what it can on its next
// publish tick and forgets the rest. Both fields are fixed-width bitmaps of
// length `committee_size`.
type CommitteeAttestationPartsMetadata struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Slot            int32                  `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"` // redundant with attestation_data per spec
	AttestationData []byte                 `protobuf:"bytes,2,opt,name=attestation_data,json=attestationData,proto3" json:"attestation_data,omitempty"`
	Available       []byte                 `protobuf:"bytes,3,opt,name=available,proto3" json:"available,omitempty"` // bitmap[committee_size]
	Requests        []byte                 `protobuf:"bytes,4,opt,name=requests,proto3" json:"requests,omitempty"`   // bitmap[committee_size]
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CommitteeAttestationPartsMetadata) Reset() {
	*x = CommitteeAttestationPartsMetadata{}
	mi := &file_attestation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitteeAttestationPartsMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitteeAttestationPartsMetadata) ProtoMessage() {}

func (x *CommitteeAttestationPartsMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_attestation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitteeAttestationPartsMetadata.ProtoReflect.Descriptor instead.
func (*CommitteeAttestationPartsMetadata) Descriptor() ([]byte, []int) {
	return file_attestation_proto_rawDescGZIP(), []int{2}
}

func (x *CommitteeAttestationPartsMetadata) GetSlot() int32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *CommitteeAttestationPartsMetadata) GetAttestationData() []byte {
	if x != nil {
		return x.AttestationData
	}
	return nil
}

func (x *CommitteeAttestationPartsMetadata) GetAvailable() []byte {
	if x != nil {
		return x.Available
	}
	return nil
}

func (x *CommitteeAttestationPartsMetadata) GetRequests() []byte {
	if x != nil {
		return x.Requests
	}
	return nil
}

// ControlEnvelope is the PartsMetadata blob: one envelope per (peer, tick)
// carrying one CommitteeAttestationPartsMetadata per unique AttestationData
// the sender has state for.
type ControlEnvelope struct {
	state         protoimpl.MessageState               `protogen:"open.v1"`
	Metadatas     []*CommitteeAttestationPartsMetadata `protobuf:"bytes,1,rep,name=metadatas,proto3" json:"metadatas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlEnvelope) Reset() {
	*x = ControlEnvelope{}
	mi := &file_attestation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlEnvelope) ProtoMessage() {}

func (x *ControlEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_attestation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlEnvelope.ProtoReflect.Descriptor instead.
func (*ControlEnvelope) Descriptor() ([]byte, []int) {
	return file_attestation_proto_rawDescGZIP(), []int{3}
}

func (x *ControlEnvelope) GetMetadatas() []*CommitteeAttestationPartsMetadata {
	if x != nil {
		return x.Metadatas
	}
	return nil
}

// BatchedAttestationEnvelope is the PartialMessage blob: one envelope per
// (peer, tick) carrying one BatchedAttestation per unique AttestationData
// being forwarded.
type BatchedAttestationEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Batches       []*BatchedAttestation  `protobuf:"bytes,1,rep,name=batches,proto3" json:"batches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchedAttestationEnvelope) Reset() {
	*x = BatchedAttestationEnvelope{}
	mi := &file_attestation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchedAttestationEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchedAttestationEnvelope) ProtoMessage() {}

func (x *BatchedAttestationEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_attestation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchedAttestationEnvelope.ProtoReflect.Descriptor instead.
func (*BatchedAttestationEnvelope) Descriptor() ([]byte, []int) {
	return file_attestation_proto_rawDescGZIP(), []int{4}
}

func (x *BatchedAttestationEnvelope) GetBatches() []*BatchedAttestation {
	if x != nil {
		return x.Batches
	}
	return nil
}

var File_attestation_proto protoreflect.FileDescriptor

const file_attestation_proto_rawDesc = "" +
	"\n" +
	"\x11attestation.proto\x12\vattestation\"\xcf\x01\n" +
	"\vAttestation\x12\x19\n" +
	"\bnode_num\x18\x01 \x01(\x05R\anodeNum\x12\x19\n" +
	"\bslot_num\x18\x02 \x01(\x05R\aslotNum\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x12\x1b\n" +
	"\tmsg_index\x18\x06 \x01(\x05R\bmsgIndex\x12\x1c\n" +
	"\tsignature\x18\a \x01(\fR\tsignatureJ\x04\b\x03\x10\x04J\x04\b\x05\x10\x06R\x12publish_at_unix_msR\x1bexpected_publish_at_unix_ms\"\x8a\x01\n" +
	"\x12BatchedAttestation\x12)\n" +
	"\x10attestation_data\x18\x01 \x01(\fR\x0fattestationData\x12)\n" +
	"\x10attestor_indices\x18\x02 \x03(\rR\x0fattestorIndices\x12\x1e\n" +
	"\n" +
	"signatures\x18\x03 \x03(\fR\n" +
	"signatures\"\x9c\x01\n" +
	"!CommitteeAttestationPartsMetadata\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\x05R\x04slot\x12)\n" +
	"\x10attestation_data\x18\x02 \x01(\fR\x0fattestationData\x12\x1c\n" +
	"\tavailable\x18\x03 \x01(\fR\tavailable\x12\x1a\n" +
	"\brequests\x18\x04 \x01(\fR\brequests\"_\n" +
	"\x0fControlEnvelope\x12L\n" +
	"\tmetadatas\x18\x01 \x03(\v2..attestation.CommitteeAttestationPartsMetadataR\tmetadatas\"W\n" +
	"\x1aBatchedAttestationEnvelope\x129\n" +
	"\abatches\x18\x01 \x03(\v2\x1f.attestation.BatchedAttestationR\abatchesB-Z+github.com/ethp2p/simlab/cmd/attestation/pbb\x06proto3"

var (
	file_attestation_proto_rawDescOnce sync.Once
	file_attestation_proto_rawDescData []byte
)

func file_attestation_proto_rawDescGZIP() []byte {
	file_attestation_proto_rawDescOnce.Do(func() {
		file_attestation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_attestation_proto_rawDesc), len(file_attestation_proto_rawDesc)))
	})
	return file_attestation_proto_rawDescData
}

var file_attestation_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_attestation_proto_goTypes = []any{
	(*Attestation)(nil),                       // 0: attestation.Attestation
	(*BatchedAttestation)(nil),                // 1: attestation.BatchedAttestation
	(*CommitteeAttestationPartsMetadata)(nil), // 2: attestation.CommitteeAttestationPartsMetadata
	(*ControlEnvelope)(nil),                   // 3: attestation.ControlEnvelope
	(*BatchedAttestationEnvelope)(nil),        // 4: attestation.BatchedAttestationEnvelope
}
var file_attestation_proto_depIdxs = []int32{
	2, // 0: attestation.ControlEnvelope.metadatas:type_name -> attestation.CommitteeAttestationPartsMetadata
	1, // 1: attestation.BatchedAttestationEnvelope.batches:type_name -> attestation.BatchedAttestation
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_attestation_proto_init() }
func file_attestation_proto_init() {
	if File_attestation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_attestation_proto_rawDesc), len(file_attestation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_attestation_proto_goTypes,
		DependencyIndexes: file_attestation_proto_depIdxs,
		MessageInfos:      file_attestation_proto_msgTypes,
	}.Build()
	File_attestation_proto = out.File
	file_attestation_proto_goTypes = nil
	file_attestation_proto_depIdxs = nil
}
